FROM fc-base:23
MAINTAINER ogutierrez@redhat.com

ARG DISTRIBUTION=23

# Install needed build packages
RUN dnf install -y tar xz git autoconf automake autoconf-archive python2-devel dbus-python pygobject2 libvirt-python python-websockify numpy python-crypto gjs rpm-build dconf desktop-file-utils python-dbusmock

# Add build script
ADD data/${DISTRIBUTION}/scripts/build-package.sh ~/build-package.sh

# Expose SSH port
EXPOSE 22

# Execute SSH server
ENTRYPOINT ["/usr/sbin/sshd", "-D"]