# Copyright (C) 2016 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the licence, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# Author: Oliver Gutiérrez <ogutierrez@redhat.com>

- hosts: build
  tasks:
    - name: Remove previously built packages
      file: path=/home/vagrant/rpmbuild/RPMS/noarch/ state=absent
    - name: Remove previously checked out sources
      file: path=/home/vagrant/fc-admin state=absent
    - name: Clone fleet commander admin sources
      git: repo={{ repo_address }}
         dest=/home/vagrant/fc-admin
         depth=1
         version={{ repo_version }}
    - name: Initialize repository submodules
      command: git submodule init
      args:
        chdir: /home/vagrant/fc-admin
    - name: Update repository submodules
      command: git submodule update
      args:
        chdir: /home/vagrant/fc-admin
    - name: Autogen tool
      shell: ./autogen.sh
      environment:
        PATH: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
      args:
        chdir: /home/vagrant/fc-admin
    - name: Run tests
      command: make check
      args:
        chdir: /home/vagrant/fc-admin
    - name: Run dist tests
      command: make distcheck
      environment:
        PATH: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
      args:
        chdir: /home/vagrant/fc-admin
    - name: Make
      command: make
      args:
        chdir: /home/vagrant/fc-admin
    - name: Make dist
      command: make dist
      args:
        chdir: /home/vagrant/fc-admin
    - name: Ensure sources directory exists
      file: path=/home/vagrant/rpmbuild/SOURCES state=directory
    - name: Copy tarball distribution file to RPM build sources
      shell: cp /home/vagrant/fc-admin/fleet-commander-admin-*.tar.xz /home/vagrant/rpmbuild/SOURCES/
    - name: Build RPM package
      shell: rpmbuild -ba /home/vagrant/fc-admin/fleet-commander-admin.spec
      environment:
        PATH: /bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
      args:
        chdir: /home/vagrant/fc-admin
    - name: Remove previous local RPM packages
      local_action: file path=../../packages/ state=absent
    - name: Fetch RPM packages
      synchronize: mode=pull src=/home/vagrant/rpmbuild/RPMS/noarch/ dest=../../packages/
