# Copyright (C) 2016 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the licence, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# Author: Oliver Gutiérrez <ogutierrez@redhat.com>


# Create link for fleet-commander-admin in httpd
# if [ ! -L /etc/httpd/conf.d/fleet-commander-apache.conf ]; then
#     ln -s /etc/xdg/fleet-commander-apache.conf /etc/httpd/conf.d/
# fi

- hosts: admin
  become: true
  tasks:
    - name: Remove any previous fleet commander installation
      dnf: name=fleet-commander-admin state=absent
    - name: Install fleet commander admin package
      command: dnf install -y /home/vagrant/rpms/fleet-commander-admin*.rpm
    - name: Restart apache web server
      service: name=httpd state=restarted