# Copyright (C) 2016 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the licence, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# Author: Oliver Gutiérrez <ogutierrez@redhat.com>

# Package list needed for building fleet-commander
# tar xz git autoconf automake autoconf-archive python2-devel dbus-python \
# pygobject2 libvirt-python python-websockify numpy python-crypto \
# gjs rpm-build dconf desktop-file-utils python-dbusmock && dnf clean all

- hosts: build
  gather_facts: false
  become: true
  tasks:
    - name: Install ansible needed packages
      raw: dnf install -y python2 python2-dnf libselinux-python
    - name: Install build dependences
      dnf: name={{item}} state=present
      with_items:
        - tar
        - xz
        - git
        - autoconf
        - automake
        - autoconf-archive
        - python2-devel
        - dbus-python
        - pygobject2
        - libvirt-python
        - python-websockify
        - numpy
        - python-crypto
        - gjs
        - rpm-build
        - dconf
        - desktop-file-utils
        - python-dbusmock
        - dbus-x11

- hosts: admin
  gather_facts: false
  become: true
  tasks:
    - name: Install ansible needed packages
      raw: sudo dnf install -y python2 python2-dnf libselinux-python \
    - name: Install admin dependences
      dnf: name={{item}} state=present
      with_items:
        - httpd
    - name: Enable apache web server
      service: name=httpd enabled=yes
    - name: Start apache web server
      service: name=httpd state=started

- hosts: hyper
  gather_facts: false
  become: true
  tasks:
    - name: Install ansible needed packages
      raw: sudo dnf install -y python2 python2-dnf libselinux-python \
    - name: Install hypervisor dependences
      dnf: name={{item}} state=present
      with_items:
        - libvirt
        - vagrant
        - vagrant-libvirt
        - ansible
    - name: Enable libvirtd service
      service: name=libvirtd enabled=yes
    - name: Start libvirtd service
      service: name=libvirtd state=started
    - name: Create logger virtual machine directory
      file: path=/home/vagrant/logger/ state=directory owner=vagrant
    - name: Copy Vagrantfile for logger virtual machine directory
      copy: src=../config/Vagrantfile.logger dest=/home/vagrant/logger/Vagrantfile owner=vagrant
    - name: Download Fedora box file from Vagrant Atlas
      get_url: url=https://download.fedoraproject.org/pub/fedora/linux/releases/23/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-23-20151030.x86_64.vagrant-libvirt.box dest=/tmp/fedora.box
    - name: Add box to vagrant boxes
      command: vagrant box add /tmp/fedora.box --name fedora/23-cloud-base --force
    - name: Remove box file
      file: path=/tmp/fedora.box state=absent
    - name: Copy vagrant user public key to root user
      command: cp /home/vagrant/.ssh/authorized_keys /root/.ssh/

- hosts: logger
  gather_facts: false
  become: true
  tasks:
    - name: Install ansible needed packages
      raw: sudo dnf install -y python2 python2-dnf libselinux-python
    - name: Copy RPM packages
      synchronize: src=../../packages/ dest=/home/vagrant/packages/
    - name: Install fleet commander logger package
      shell: dnf install -y fleet-commander-logger*.rpm
      args:
        chdir: /home/vagrant/packages/
    - name: Disable graphical console on boot
      lineinfile: dest=/etc/default/grub regexp='^GRUB_CMDLINE_LINUX*' line='GRUB_CMDLINE_LINUX="no_timer_check console=tty1 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 console=ttyS1 nomodeset"'
    - name: Update GRUB configuration
      command: grub2-mkconfig -o /boot/grub2/grub.cfg
    - name: Enable autologin in logger machine
      lineinfile: dest=/usr/lib/systemd/system/getty@.service regexp='^ExecStart\=.*' line='ExecStart=-/sbin/agetty --autologin vagrant --noclear %I $TERM'
    - name: Copy logger helper script
      copy: src=../scripts/logger_helper.sh dest=/home/vagrant/logger_helper.sh owner=vagrant mode=0755
    - name: Add logger helper script to profiles for autostart on login
      lineinfile: dest=/etc/profile line='/home/vagrant/logger_helper.sh'
