# Copyright (C) 2016 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the licence, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# Author: Oliver Gutiérrez <ogutierrez@redhat.com>

# Package list needed for building fleet-commander
# tar xz git autoconf automake autoconf-archive python2-devel dbus-python \
# pygobject2 libvirt-python python-websockify numpy python-crypto \
# gjs rpm-build dconf desktop-file-utils python-dbusmock && dnf clean all

- hosts: build
  gather_facts: false
  tasks:
    - name: Needed packages installation
      raw: sudo dnf install -y python2 python2-dnf libselinux-python \
        tar xz git autoconf automake autoconf-archive python2-devel \
        dbus-python pygobject2 libvirt-python python-websockify numpy \
        python-crypto gjs rpm-build dconf desktop-file-utils python-dbusmock

- hosts: admin
  gather_facts: false
  tasks:
    - name: Needed packages installation
      raw: sudo dnf install -y python2 python2-dnf libselinux-python \
        httpd
    - name: Enable apache web server
      service: name=httpd enabled=yes
    - name: Start apache web server
      service: name=httpd state=started

    # - name: install python and deps for ansible modules
    #   raw: sudo dnf install -y python2 python2-dnf libselinux-python
    # - name: Checking latest version for package git
    #   dnf: name=git state=latest
    # - name: Checking latest version for package tar
    #   dnf: name=tar state=latest
    # - name: Checking latest version for package xz
    #   dnf: name=xz state=latest
    # - name: Checking latest version for package autoconf
    #   dnf: name=autoconf state=latest
    # - name: Checking latest version for package automake
    #   dnf: name=automake state=latest
    # - name: Checking latest version for package autoconf-archive
    #   dnf: name=autoconf-archive state=latest
    # - name: Checking latest version for package python2-devel
    #   dnf: name=python2-devel state=latest
    # - name: Checking latest version for package dbus-python
    #   dnf: name=dbus-python state=latest
    # - name: Checking latest version for package pygobject2
    #   dnf: name=pygobject2 state=latest
    # - name: Checking latest version for package libvirt-python
    #   dnf: name=libvirt-python state=latest
    # - name: Checking latest version for package python-websockify
    #   dnf: name=python-websockify state=latest
    # - name: Checking latest version for package numpy
    #   dnf: name=numpy state=latest
    # - name: Checking latest version for package pyton-crypto
    #   dnf: name=python-crypto state=latest
    # - name: Checking latest version for package gjs
    #   dnf: name=gjs state=latest
    # - name: Checking latest version for package rpm-build
    #   dnf: name=rpm-build state=latest
    # - name: Checking latest version for package dconf
    #   dnf: name=dconf state=latest
    # - name: Checking latest version for package desktop-file-utils
    #   dnf: name=desktop-file-utils state=latest
    # - name: Checking latest version for package python-dbusmock
    #   dnf: name=python-dbusmock state=latest

